[2020-06-18 22:57:49,633] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: mis.save_processed 2020-06-19T02:57:37.436324+00:00 [queued]>
[2020-06-18 22:57:49,678] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: mis.save_processed 2020-06-19T02:57:37.436324+00:00 [queued]>
[2020-06-18 22:57:49,679] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 22:57:49,679] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 22:57:49,679] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 22:57:49,698] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_processed> on 2020-06-19T02:57:37.436324+00:00
[2020-06-18 22:57:49,701] {standard_task_runner.py:53} INFO - Started process 16268 to run task
[2020-06-18 22:57:49,787] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: mis.save_processed 2020-06-19T02:57:37.436324+00:00 [running]> strx
[2020-06-18 22:57:49,817] {logging_mixin.py:112} INFO - Saving processed...
[2020-06-18 22:57:50,863] {python_operator.py:114} INFO - Done. Returned value was: integrate_data
[2020-06-18 22:57:50,927] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=mis, task_id=save_processed, execution_date=20200619T025737, start_date=20200619T025749, end_date=20200619T025750
