[2020-06-08 13:43:02,595] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: python_test.integrate_data 2020-06-06T00:00:00+00:00 [queued]>
[2020-06-08 13:43:02,610] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: python_test.integrate_data 2020-06-06T00:00:00+00:00 [queued]>
[2020-06-08 13:43:02,610] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 13:43:02,610] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-08 13:43:02,610] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-08 13:43:02,752] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): integrate_data> on 2020-06-06T00:00:00+00:00
[2020-06-08 13:43:02,755] {standard_task_runner.py:53} INFO - Started process 6579 to run task
[2020-06-08 13:43:02,916] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: python_test.integrate_data 2020-06-06T00:00:00+00:00 [running]> strx
[2020-06-08 13:43:02,929] {logging_mixin.py:112} INFO - integrate_data 2020-06-06
[2020-06-08 13:43:07,934] {python_operator.py:114} INFO - Done. Returned value was: integrate_data
[2020-06-08 13:43:08,093] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=python_test, task_id=integrate_data, execution_date=20200606T000000, start_date=20200608T174302, end_date=20200608T174308
[2020-06-08 13:43:12,430] {logging_mixin.py:112} INFO - [2020-06-08 13:43:12,429] {local_task_job.py:103} INFO - Task exited with return code 0
