[2020-06-18 21:07:36,960] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: mis.save_processed 2020-06-19T01:03:27+00:00 [queued]>
[2020-06-18 21:07:37,006] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: mis.save_processed 2020-06-19T01:03:27+00:00 [queued]>
[2020-06-18 21:07:37,006] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 21:07:37,006] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 21:07:37,007] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 21:07:37,039] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_processed> on 2020-06-19T01:03:27+00:00
[2020-06-18 21:07:37,043] {standard_task_runner.py:53} INFO - Started process 18882 to run task
[2020-06-18 21:07:37,187] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: mis.save_processed 2020-06-19T01:03:27+00:00 [running]> strx
[2020-06-18 21:07:37,221] {logging_mixin.py:112} INFO - Saving processed...
[2020-06-18 21:07:39,304] {python_operator.py:114} INFO - Done. Returned value was: integrate_data
[2020-06-18 21:07:39,460] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=mis, task_id=save_processed, execution_date=20200619T010327, start_date=20200619T010736, end_date=20200619T010739
[2020-06-18 21:07:46,913] {logging_mixin.py:112} INFO - [2020-06-18 21:07:46,912] {local_task_job.py:103} INFO - Task exited with return code 0
